---
title: "CA_prop99"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
set.seed(42)
install.packages("didimputation")
library(didimputation)

library(seq.sdid)
data(CA_prop99)
```

```{r}
panel <- to_wide(
  CA_prop99,
  unit = "State", time = "Year",
  outcome = "PacksPerCapita",
  treatment = "treated"
)
panel_avg <- prepare_wide(panel, "unit")
```


```{r}
s2 <- estimate_s2(panel$Y, panel$W)

est <- sequential_estimator(
  panel_avg = panel_avg,
  level = "unit",
  s2 = s2,
  type = "both",
  aggregate_effect = aggregate_by_weight
)
print(est, 3)
```

```{r}
se <- vcov(est, panel, B = 1000)
print(se)
```

```{r}
plot(
  est, se, NULL,
  error_bar_width = 0.4, xlab = "Lags",
  legend_position = "right"
)
```


```{r}
library(didimputation)
library(data.table)
data.table::setDT(CA_prop99)

CA_prop99[, "g"] <- 0
CA_prop99[State == "California", "g"] <- 1989
CA_prop99[State == "Wyoming", "g"] <- 1993


did_imputation(
  data = CA_prop99, 
  idname = "State",
  tname = "Year",
  yname = "PacksPerCapita",
  gname = "g",
  horizon = TRUE
)


```
