---
title: "Community Health Centers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Community Health Centers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

To install `MCPanel` package you need to run the following chunk:

```{r}
#install.packages("devtools")
#install.packages("latex2exp")
#devtools::install_github("susanathey/MCPanel")
```

```{r setup}
library("seq.sdid") 
library(xtable)
set.seed(42)
```

```{r}
data(CHC)
panel <- to_wide(CHC,
  unit = 1, time = 3, outcome = 2,
  treatment = 4, contr_covs = c(5), treat_covs = c(),
  population = 6
)
```

```{r}
s2 <- estimate_s2(panel$Y, panel$W, panel$X$popwt, wls = FALSE)

panel$X$popwt <- panel$X$popwt / 10000
panel_avg <- prepare_wide(panel)
#s2 <- 5000
```


```{r}
est <- sequential_estimator(panel_avg, "cohort",
                            s2 = s2, "both")
```

```{r}
se <- vcov(est, panel, B = 1000, return_tau_b = TRUE)
```

```{r, fig.retina = 3, fig.width=16, fig.height=9, out.height = "100%", out.width = "100%"}
plot_chc_effect(est$tau_sdid, se$tau_b$tau_b_sdid, save_pdf = TRUE)
```

# Simulation
## 80 \% signal: the standard deviation of interactive FE is 4 times than std of FE. 
```{r}
params <- estimate_dgp_chc(
  panel = panel, signal_share = 0.8,
  scale = 4, rank = 5
)
panel_sim <- list(
  Y = params$L,
  W = params$W,
  X = params$X,
  never_treat = "2500"
)
```

```{r}
M <- 10
W_avg <- prepare_wide(panel)$W_avg
tau_array_sdid <- array(dim = c(max(rowSums(W_avg)), M))
tau_array_did <- array(dim = c(max(rowSums(W_avg)), M))
t_stat_sdid <- array(dim = c(max(rowSums(W_avg)), M))
t_stat_did <- array(dim = c(max(rowSums(W_avg)), M))

for (m in 1:M) {
  Y <- simulate_dgp_chc(params)$Y
  panel_b <- panel_sim
  panel_b$Y <- Y
  s2 <- estimate_s2(Y, panel_b$W, panel_b$X$popwt)
  #s2 <- params$sigma_2
  panel_avg <- prepare_wide(panel_b, "cohort", boot = TRUE)
  panel_avg$W_avg <- W_avg

  est <- sequential_estimator(panel_avg, "cohort",
                              s2 = s2, "both")
  se <- vcov(est, panel_b, 100)
  tau_array_sdid[, m] <- est$tau_sdid
  tau_array_did[, m] <- est$tau_did
  t_stat_sdid[, m] <- est$tau_sdid / se$se_sdid
  t_stat_did[, m] <- est$tau_did / se$se_did
}
```

```{r}
create_tables(
  tau_array_sdid,
  tau_array_did,
  t_stat_sdid,
  t_stat_did,
  "CHC",
  0.8,
  TRUE
)
```

```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
plot_t_stat(
  t_stat_array = t_stat_sdid,
  lags = c(0, 4, 7),
  type = "sdid",
  sim_name = "CHC",
  signal_share = 0.8,
  breaks = 50,
  save_pdf = TRUE
)
```

```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
plot_t_stat(
  t_stat_array = t_stat_did,
  lags = c(0, 4, 7),
  type = "did",
  sim_name = "CHC",
  signal_share = 0.8,
  breaks = 50,
  save_pdf = TRUE
)
```


## 0 \% signal: no interactive FE
```{r}
params <- estimate_dgp_chc(
  panel = panel, signal_share = 0.0,
  scale = 4, rank = 5
)
panel_sim <- list(
  Y = params$L,
  W = params$W,
  X = params$X,
  never_treat = "2500"
)
```

```{r}
M <- 10
W_avg <- prepare_wide(panel)$W_avg
tau_array_sdid <- array(dim = c(max(rowSums(W_avg)), M))
tau_array_did <- array(dim = c(max(rowSums(W_avg)), M))
t_stat_sdid <- array(dim = c(max(rowSums(W_avg)), M))
t_stat_did <- array(dim = c(max(rowSums(W_avg)), M))

for (m in 1:M) {
  Y <- simulate_dgp_chc(params)$Y
  panel_b <- panel_sim
  panel_b$Y <- Y
  s2 <- estimate_s2(Y, panel_b$W, panel_b$X$popwt)
  #s2 <- params$sigma_2
  panel_avg <- prepare_wide(panel_b, "cohort", boot = TRUE)
  panel_avg$W_avg <- W_avg

  est <- sequential_estimator(panel_avg, "cohort",
                              s2 = s2, "both")
  se <- vcov(est, panel_b, 100)
  tau_array_sdid[, m] <- est$tau_sdid
  tau_array_did[, m] <- est$tau_did
  t_stat_sdid[, m] <- est$tau_sdid / se$se_sdid
  t_stat_did[, m] <- est$tau_did / se$se_did
}
```

```{r}
create_tables(
  tau_array_sdid,
  tau_array_did,
  t_stat_sdid,
  t_stat_did,
  "CHC",
  0.0,
  TRUE
)
```

```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
plot_t_stat(
  t_stat_array = t_stat_sdid,
  lags = c(0, 4, 7),
  type = "sdid",
  sim_name = "CHC",
  signal_share = 0,
  breaks = 50,
  save_pdf = TRUE
)
```

```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
plot_t_stat(
  t_stat_array = t_stat_did,
  lags = c(0, 4, 7),
  type = "did",
  sim_name = "CHC",
  signal_share = 0,
  breaks = 50,
  save_pdf = TRUE
)
```

