# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Penalty for SSDiD
NULL

base_estimator <- function(Y, n_j, penalty, s2 = -1.0, type = "sdid") {
    .Call(`_seq_sdid_base_estimator`, Y, n_j, penalty, s2, type)
}

