# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the base synthetic diff-in-diff or diff-in-diff estimate.
#' @name base_estimator
#' @description
#' The armadillo implementation of `base_estimator` algorithm.
#' The bottom right cell is the only cell being treated: W_it = 1.
#' @param Y :            Numeric arma::mat. A submatrix of outcomes with one treated obs in the bottom right corner.
#' @param coh_weights :  Numeric arma::vec. The vector of cohort weights. It might be the number of units in cohorts or
#'                                          the cohort weights, usually just cohort population.
#' @param penalty :      double.
#' @param s2 :           double or -1.0. The upper bound estimate of noise variance.
#' @param type :         std::string. Type of the estimator should be `sdid` or `did`.
#' @param fast:          bool. If true, fast matrix inversion is conducted.
#'
#' @return               NumericVector size of 2. The first element is the treatment effect,
#'                                         the second one is the asymptotic variance.
base_estimator <- function(Y, coh_weights, penalty, s2 = -1.0, type = "sdid", fast = FALSE) {
    .Call(`_seq_sdid_base_estimator`, Y, coh_weights, penalty, s2, type, fast)
}

